### ISSUE TITLE
Getting "Error generating the bundle" on build

### ISSUE THREAD

**Issue by MihaMarkic** [madskristensen/WebEssentials2013#1077]
VS2013 Update 2 RTM, WE 2.1. I am getting these dialogs upon build:

---
## OK   

Build output says:

18.5.2014 17:03:57: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__21.MoveNext()

The solution would still build and run though.

**Comment by izrake** [comment]
I am getting this error while creating setup and deployment for my application.
If any one fixed the issue please share the fix.

9/8/2017 1:33:04 PM: An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
at MadsKristensen.EditorExtensions.BundleFilesMenu.d__12.MoveNext()
9/8/2017 1:33:04 PM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.d__f.MoveNext()
