### ISSUE TITLE
Cant install on visual studio 2013 ultimate edition 

### ISSUE THREAD

**Issue by thak123** [madskristensen/WebEssentials2013#1211]
6/23/2014 9:33:03 AM - Microsoft VSIX Installer
6/23/2014 9:33:03 AM - -------------------------------------------
6/23/2014 9:33:03 AM - Initializing Install...
6/23/2014 9:33:03 AM - Extension Details...
6/23/2014 9:33:03 AM -  Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
6/23/2014 9:33:03 AM -  Name            : Web Essentials 2013 for Update 2
6/23/2014 9:33:03 AM -  Author          : Mads Kristensen
6/23/2014 9:33:03 AM -  Version         : 2.2
6/23/2014 9:33:03 AM -  Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 2 RTM
6/23/2014 9:33:03 AM -  Locale          : en-US
6/23/2014 9:33:03 AM -  MoreInfoURL     : http://vswebessentials.com/
6/23/2014 9:33:03 AM -  InstalledByMSI  : False
6/23/2014 9:33:03 AM -  SupportedFrameworkVersionRange : [4.5]
6/23/2014 9:33:03 AM - 
6/23/2014 9:33:03 AM -  Supported Products : 
6/23/2014 9:33:03 AM -      Microsoft.VisualStudio.Pro
6/23/2014 9:33:03 AM -          Version : [12.0.30501,13.0)
6/23/2014 9:33:03 AM -      Microsoft.VisualStudio.VWDExpress
6/23/2014 9:33:03 AM -          Version : [12.0.30501,13.0)
6/23/2014 9:33:03 AM - 
6/23/2014 9:33:03 AM -  References      : 
6/23/2014 9:33:03 AM -      -------------------------------------------------------
6/23/2014 9:33:03 AM -      Identifier   : Microsoft.VisualStudio.MPF.12.0
6/23/2014 9:33:03 AM -      Name         : Visual Studio MPF 12.0
6/23/2014 9:33:03 AM -      Version      : [12.0,13.0)
6/23/2014 9:33:03 AM -      MoreInfoURL  : 
6/23/2014 9:33:03 AM -      Nested       : No
6/23/2014 9:33:03 AM - 
6/23/2014 9:33:03 AM - 
6/23/2014 9:33:03 AM - Searching for applicable products...
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio Ultimate 2012
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio Premium 2012 
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio Professional 2012
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio Premium 2013
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio Professional 2013
6/23/2014 9:33:03 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
6/23/2014 9:33:03 AM - Found installed product - Global Location
6/23/2014 9:33:03 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

got this error and cant find the web essential on the products and extension window

**Comment by sager** [comment]
I tried with Update 4 but no luck , I have VS 2013 Ultimate Update 4:
```bat
2015-05-07 15:24:33 - Microsoft VSIX Installer
2015-05-07 15:24:33 - -------------------------------------------
2015-05-07 15:24:33 - Initializing Install...
2015-05-07 15:24:33 - Extension Details...
2015-05-07 15:24:33 - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
2015-05-07 15:24:33 - 	Name            : Web Essentials 2013 for Update 4
2015-05-07 15:24:33 - 	Author          : Mads Kristensen
2015-05-07 15:24:33 - 	Version         : 2.5.1
2015-05-07 15:24:33 - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4 RC
2015-05-07 15:24:33 - 	Locale          : en-US
2015-05-07 15:24:33 - 	MoreInfoURL     : http://vswebessentials.com/
2015-05-07 15:24:33 - 	InstalledByMSI  : False
2015-05-07 15:24:33 - 	SupportedFrameworkVersionRange : [4.5]
2015-05-07 15:24:33 - 
2015-05-07 15:24:33 - 	Supported Products : 
2015-05-07 15:24:33 - 		Microsoft.VisualStudio.Pro
2015-05-07 15:24:33 - 			Version : [12.0.31101]
2015-05-07 15:24:33 - 
2015-05-07 15:24:33 - 	References      : 
2015-05-07 15:24:33 - 		-------------------------------------------------------
2015-05-07 15:24:33 - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
2015-05-07 15:24:33 - 		Name         : Visual Studio MPF 12.0
2015-05-07 15:24:33 - 		Version      : [12.0,13.0)
2015-05-07 15:24:33 - 		MoreInfoURL  : 
2015-05-07 15:24:33 - 		Nested       : No
2015-05-07 15:24:33 - 
2015-05-07 15:24:33 - 
2015-05-07 15:24:33 - Searching for applicable products...
2015-05-07 15:24:35 - Found installed product - Microsoft Visual Studio Ultimate 2013
2015-05-07 15:24:35 - Found installed product - Microsoft Visual Studio Premium 2013
2015-05-07 15:24:35 - Found installed product - Microsoft Visual Studio Professional 2013
2015-05-07 15:24:35 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
2015-05-07 15:24:35 - Found installed product - Global Location
2015-05-07 15:24:35 - Found installed product - ssms
2015-05-07 15:24:35 - Found installed product - ssms
2015-05-07 15:24:35 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   w VSIXInstaller.App.InitializeInstall()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
```
