### ISSUE TITLE
Exception thrown when generating bundle

### ISSUE THREAD

**Issue by peters** [madskristensen/WebEssentials2013#1419]
Visual studio 2013 update 3
Extension: 2.3

"Error generating bundle, please see the output windows for details"

```
19.08.2014 08:36:26: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.StartsWith(String value, StringComparison comparisonType)
   at MadsKristensen.EditorExtensions.ProjectHelpers.CreateDirectoryInProject(String path)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
19.08.2014 08:36:38: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.StartsWith(String value, StringComparison comparisonType)
   at MadsKristensen.EditorExtensions.ProjectHelpers.CreateDirectoryInProject(String path)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
19.08.2014 08:36:39: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.StartsWith(String value, StringComparison comparisonType)
   at MadsKristensen.EditorExtensions.ProjectHelpers.CreateDirectoryInProject(String path)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
```

**Comment by a-bronx** [comment]
@blowsie Same happens to me; also it happens when I rebase, and commits include bundled scripts. Looks like the background watcher gets mad when files it watches suddenly disappear when git reverts/replay commits.
