### ISSUE TITLE
Exception compiling partial

### ISSUE THREAD

**Issue by rschick** [madskristensen/WebEssentials2013#1555]
I have two scss files:

Test.scss:
@import "Partial";

_Partial.scss:
.class {
    font-weight: bold;
}

When I save the partial file, I get the following exception, which seems to prevent the compilation of the parent file so Test.css is not updated:

An exception was thrown when updating TextView property: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at MadsKristensen.EditorExtensions.Base64Vlq.GetName(Int32 index, String basePath, String[] sources)
   at MadsKristensen.EditorExtensions.Base64Vlq.<Decode>d__0.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at MadsKristensen.EditorExtensions.CssSourceMap.PopulateMap(String targetFileContents, String mapFileContents)
   at MadsKristensen.EditorExtensions.CssSourceMap.Initialize(String targetFileContents, String mapFileContents, String directory, IContentType contentType)
   at MadsKristensen.EditorExtensions.CssSourceMap.<>c__DisplayClass1.<Create>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.CssSourceMap.<Create>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Margin.CssTextViewMargin.<UpdateResults>d__1a.MoveNext()

I am running Web Essentials version 2.3.4.1.

**Comment by arootbeer** [comment]
I encountered the same exception, and discovered while debugging it that it happens when a .scss file is compiled after being *opened*, but does not happen when a .scss file is compiled after being *saved*.

When the file is compiled after being saved, `map.sources` ([here](https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/Shared/Helpers/CssSourceMap.cs#L68)) will contain e.g. this path:
`"config/_global.scss"`

When the exception occurs, `map.sources` will contain paths that look like this:
`"../../../../../../F:/MyProject/src/ui-files/source/scss/config/_global.scss"`

The critical difference appears to be that in the second case, the request is specifying that the target files reside in temporary storage (e.g. C:\Users\Administrator\AppData\Local\Temp\5a12c210-32e3-4157-8050-f78496020b5a.css), which happens to be on a different drive than my solution file.
