### ISSUE TITLE
WE makes VS2013.4 crash when opening a solution

### ISSUE THREAD

**Issue by OllyHodgson** [madskristensen/WebEssentials2013#1652]
Hello,

I'm seeing Web Essentials crash when opening a particular solution. VS2013 Professional Update 4 and Web Essentials 2.5.1. 

I visit File > Open Project >  choose the .sln file and click OK. The files appear in the solution explorer pane, and the status bar says "Web Essentials: Solution settings applied", before crashing (I get the "Visual Studio is restarting" dialog). I can load the solution without issue if I disable or uninstall Web Essentials. Rolling back to 2.5 does not fix the problem.

A quick look in event viewer gives me this:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

and:

```
Faulting application name: devenv.exe, version: 12.0.31101.0, time stamp: 0x54548724
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0x9b0
Faulting application start time: 0x01d003279438e306
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 09b85a15-6f1c-11e4-856f-080027127277
```

Please let me know what other information I can provide.

**Comment by ss27051980** [comment]
I had the exact issue with vs2013 update 4 however after uninstalling the web essentials seems to do the trick.
Thanks CrytonZylog.

**Comment by TimTheTinker** [comment]
I'm having this issue with VS 2013 update 5 and the latest WE (2013u4). Disabling WE solves the problem, although I'm left needing something to auto-compile my SASS files.
