### ISSUE TITLE
Compiling .less throws System.NotSupportedException (after successful compilation)

### ISSUE THREAD

**Issue by OllyHodgson** [madskristensen/WebEssentials2013#1682]
Hello,

I'm using WE 2.5.3 with }Microsoft Visual Studio Professional 2013, Version 12.0.31101.00 Update 4.

I make a change to a .less file, and hit Save. The .css is compiled successfully, and then an exception is thrown. My output pane looks something like this:

```
28/11/2014 14:56:18: LESS: Compiling style.less
28/11/2014 14:56:22: LESS: style.less compiled.
28/11/2014 14:56:22: An exception was thrown when updating TextView property: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at MadsKristensen.EditorExtensions.Base64Vlq.GetName(Int32 index, String basePath, String[] sources)
   at MadsKristensen.EditorExtensions.Base64Vlq.<Decode>d__0.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at MadsKristensen.EditorExtensions.CssSourceMap.PopulateMap(String targetFileContents, String mapFileContents)
   at MadsKristensen.EditorExtensions.CssSourceMap.Initialize(String targetFileContents, String mapFileContents, String directory, IContentType contentType)
   at MadsKristensen.EditorExtensions.CssSourceMap.<>c__DisplayClass1.<Create>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.CssSourceMap.<Create>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Margin.CssTextViewMargin.<UpdateResults>d__1a.MoveNext()
```

The .less and .css are in separate folders, if that makes any difference.

Let me know if you need any more information.

**Comment by ComputerWolf** [comment]
I am also seeing this error in 2.5.4. Just wondering if this was still being looked into.

**Comment by ducka** [comment]
Just found out that version 2.5.1 does not have this issue.  

https://github.com/madskristensen/WebEssentials2013/releases

For me, this problem occurred when I was compiling a less file that contained an import statement with a "../path/to/less/file.less" path.  The imported less file also needed to have less in it that produces CSS output.  If the imported file only contained mixins and variables this didn't occur.

**Comment by hyrmedia** [comment]
I suddenly began experiencing this issue a few minutes ago, after switching from one Hg branch to another and then back again, and then trying to recompile my less scripts. I do not see the error in my Output window when I build the project (and W.E. compiles all the less scripts at the end), but when I Save one particular less script, it compiles the script successfully but then throws the error in the Output window.

I can confirm that I am also doing an `import` of a less path with `../` in it, and that the `sources` in my `styles.css.map` file include a path that begins: `../E:/src/MyProjectName`... ( E: being my data drive).

**Comment by Swivelgames** [comment]
I too am running into this issue, now a year after it was reported. With a high profile meeting coming up at the end of the week, this has me a little worried.

Help me out here, guys, does anyone know of any solutions to this at the moment?

**Comment by Swivelgames** [comment]
Stacktrace:

```
10/21/2015 11:58:48 AM: LESS: Compiling _header.less
10/21/2015 11:58:48 AM: LESS: _header.less compiled.
10/21/2015 11:58:48 AM: An exception was thrown when updating TextView property: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at MadsKristensen.EditorExtensions.Base64Vlq.GetName(Int32 index, String basePath, String[] sources)
   at MadsKristensen.EditorExtensions.Base64Vlq.<Decode>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MadsKristensen.EditorExtensions.CssSourceMap.PopulateMap(String targetFileContents, String mapFileContents)
   at MadsKristensen.EditorExtensions.CssSourceMap.Initialize(String targetFileContents, String mapFileContents, String directory, IContentType contentType)
   at MadsKristensen.EditorExtensions.CssSourceMap.<>c__DisplayClass1.<Create>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.CssSourceMap.<Create>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Margin.CssTextViewMargin.<UpdateResults>d__1a.MoveNext()
10/21/2015 11:58:49 AM: LESS: main.less compiled.
```
