### ISSUE TITLE
Exception thrown after build

### ISSUE THREAD

**Issue by kfarrah** [madskristensen/WebEssentials2013#1713]
Using VS2013 and Web Essentials 2.5.3 I get following exceptions when I build my project:

An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateAllBundlesAsync>d__12.MoveNext()
12/17/2014 11:59:53 AM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.<UpdateAllSpritesAsync>d__f.MoveNext()

I'm pretty sure this did not happen with the previous version.

**Comment by pseudosavant** [comment]
I'm getting the same error for JS or CSS bundles with VS2013 and WE 2.5.3.

**Comment by Sunnyque** [comment]
I'm getting same exceptions after building c++ project. VS13, WE 2.5.3.

**Comment by gimzani** [comment]
I'm getting the same thing.

Here's some more info:

I'm using a Bundle for my JavaScript and I'm using an SCSS file.  I have NO sprites.

I'm getting this:
4/17/2015 10:58:44 AM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.<UpdateAllSpritesAsync>d__f.MoveNext()

4/17/2015 10:58:44 AM: An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateAllBundlesAsync>d__12.MoveNext()

It seems to want to compile sprites and when it can't find them, it chokes.  

Hopefully this will help find a fix?

**Comment by CabocloDeBaixos** [comment]
Im am getting the samething as well for WPF project...

**Comment by shakehar** [comment]
I don't think is is project specific, I am getting this on a winform as well as a WCF project.

**Comment by gimzani** [comment]
Hey all - I'm not getting this anymore on any of my projects after updating VS.  You might try to get the latest updates and see if the problem goes away like mine did.

**Comment by savornicesei** [comment]
On Win 7, VS 2013 Professional Update 5, Web Essentials 2.6.36 I still get the Web Essentials error message even if I open a windows forms project:

10/26/2015 6:31:13 PM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.<UpdateAllSpritesAsync>d__f.MoveNext()
10/26/2015 6:31:13 PM: An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateAllBundlesAsync>d__12.MoveNext()

**Comment by pazhub** [comment]
Anyone figure this one out? Here's my full message:

3/24/2016 2:37:46 PM: An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateAllBundlesAsync>d__12.MoveNext()
3/24/2016 2:37:46 PM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.<UpdateAllSpritesAsync>d__f.MoveNext()

**Comment by rageit** [comment]
Still getting it for Visual Studio Ultimate 2013, Update 5

8/24/2016 11:42:04 AM: An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateAllBundlesAsync>d__12.MoveNext()
8/24/2016 11:42:04 AM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.<UpdateAllSpritesAsync>d__f.MoveNext()

**Comment by izrake** [comment]
I am getting this error while creating setup and deployment for my application.
If any one fixed the issue please share the fix.

**9/8/2017 1:33:04 PM: An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateAllBundlesAsync>d__12.MoveNext()
9/8/2017 1:33:04 PM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.<UpdateAllSpritesAsync>d__f.MoveNext()**

**Comment by mukunku** [comment]
I'm also getting this error:

12/12/2017 1:35:25 PM: An exception was thrown when Web Essentials: Updating Bundles...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateAllBundlesAsync>d__12.MoveNext()
12/12/2017 1:35:25 PM: An exception was thrown when Web Essentials: Updating Sprites...: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Images.SpriteImageMenu.<UpdateAllSpritesAsync>d__f.MoveNext()
