### ISSUE TITLE
Unable to install for vs 2013 ultimate windows 8.1

### ISSUE THREAD

**Issue by msender** [madskristensen/WebEssentials2013#1724]
Unable to install for vs 2013 ultimate windows 8.1

**Comment by Charles-521** [comment]
I have the same issue, attached is the install log:

1/7/2015 4:52:06 PM - Microsoft VSIX Installer
1/7/2015 4:52:06 PM - -------------------------------------------
1/7/2015 4:52:06 PM - Initializing Install...
1/7/2015 4:52:07 PM - Extension Details...
1/7/2015 4:52:07 PM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
1/7/2015 4:52:07 PM - 	Name            : Web Essentials 2013 for Update 4
1/7/2015 4:52:07 PM - 	Author          : Mads Kristensen
1/7/2015 4:52:07 PM - 	Version         : 2.5.3
1/7/2015 4:52:07 PM - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4
1/7/2015 4:52:07 PM - 	Locale          : en-US
1/7/2015 4:52:07 PM - 	MoreInfoURL     : http://vswebessentials.com/
1/7/2015 4:52:07 PM - 	InstalledByMSI  : False
1/7/2015 4:52:07 PM - 	SupportedFrameworkVersionRange : [4.5]
1/7/2015 4:52:07 PM - 
1/7/2015 4:52:07 PM - 	Supported Products : 
1/7/2015 4:52:07 PM - 		Microsoft.VisualStudio.Pro
1/7/2015 4:52:07 PM - 			Version : [12.0.31101]
1/7/2015 4:52:07 PM - 		Microsoft.VisualStudio.VWDExpress
1/7/2015 4:52:07 PM - 			Version : [12.0.31101]
1/7/2015 4:52:07 PM - 
1/7/2015 4:52:07 PM - 	References      : 
1/7/2015 4:52:07 PM - 		-------------------------------------------------------
1/7/2015 4:52:07 PM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
1/7/2015 4:52:07 PM - 		Name         : Visual Studio MPF 12.0
1/7/2015 4:52:07 PM - 		Version      : [12.0,13.0)
1/7/2015 4:52:07 PM - 		MoreInfoURL  : 
1/7/2015 4:52:07 PM - 		Nested       : No
1/7/2015 4:52:07 PM - 
1/7/2015 4:52:07 PM - 
1/7/2015 4:52:07 PM - Searching for applicable products...
1/7/2015 4:52:09 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
1/7/2015 4:52:09 PM - Found installed product - Microsoft Visual Studio Premium 2013
1/7/2015 4:52:09 PM - Found installed product - Microsoft Visual Studio Professional 2013
1/7/2015 4:52:09 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/7/2015 4:52:09 PM - Found installed product - Global Location
1/7/2015 4:52:09 PM - Found installed product - ssms
1/7/2015 4:52:09 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by niallthefirst** [comment]
Similar issue here. Will not install for "Premium"
02/02/2015 17:21:25 - Microsoft VSIX Installer
02/02/2015 17:21:25 - -------------------------------------------
02/02/2015 17:21:25 - Initializing Install...
02/02/2015 17:21:26 - Extension Details...
02/02/2015 17:21:26 - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
02/02/2015 17:21:26 - 	Name            : Web Essentials 2013 for Update 4
02/02/2015 17:21:26 - 	Author          : Mads Kristensen
02/02/2015 17:21:26 - 	Version         : 2.5.4
02/02/2015 17:21:26 - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4
02/02/2015 17:21:26 - 	Locale          : en-US
02/02/2015 17:21:26 - 	MoreInfoURL     : http://vswebessentials.com/
02/02/2015 17:21:26 - 	InstalledByMSI  : False
02/02/2015 17:21:26 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
02/02/2015 17:21:26 - 
02/02/2015 17:21:26 - 	Supported Products : 
02/02/2015 17:21:26 - 		Microsoft.VisualStudio.Pro
02/02/2015 17:21:26 - 			Version : [12.0.31101]
02/02/2015 17:21:26 - 		Microsoft.VisualStudio.VWDExpress
02/02/2015 17:21:26 - 			Version : [12.0.31101]
02/02/2015 17:21:26 - 
02/02/2015 17:21:26 - 	References      : 
02/02/2015 17:21:26 - 
02/02/2015 17:21:26 - Searching for applicable products...
02/02/2015 17:21:35 - Found installed product - Microsoft Visual Studio 2010 Ultimate
02/02/2015 17:21:35 - Found installed product - Microsoft Visual Studio Premium 2013
02/02/2015 17:21:35 - Found installed product - Microsoft Visual Studio Professional 2013
02/02/2015 17:21:35 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
02/02/2015 17:21:35 - Found installed product - Global Location
02/02/2015 17:21:35 - Found installed product - ssms
02/02/2015 17:21:35 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by jorupp** [comment]
Make sure you have Update 4 installed.  This is the kind of output I was getting before I did.
