### ISSUE TITLE
Invalid access to memory location 

### ISSUE THREAD

**Issue by Leefrost** [madskristensen/WebEssentials2013#1783]
This issue happens than i try to compile scss. 

26.02.2015 14:52:31: An exception was thrown when compiling D:\Repositories\Mercurial\WMT\code.sass\Content\scss\page\_content.scss: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.NetworkInformation.NetworkInformationException: Invalid access to memory location
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpConnections()
   at MadsKristensen.EditorExtensions.ServerBase.SelectAvailablePort()
   at MadsKristensen.EditorExtensions.ServerBase..ctor(String processStartArgumentsFormat, String serverPath)
   at MadsKristensen.EditorExtensions.NodeServer..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at MadsKristensen.EditorExtensions.ServerBase.<Up>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.NodeServer.<Up>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.NodeServer.<CallServiceAsync>d__1e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.NodeExecutorBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Scss.ScssCompiler.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.NodeCompilerRunner.<RunCompilerAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.CompilerRunnerBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.EditorCompilerInvoker.<InitiateCompilationAsync>d__4.MoveNext()
26.02.2015 14:52:31: An exception was thrown when compiling D:\Repositories\Mercurial\WMT\code.sass\Content\scss\page\_content.scss: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.NetworkInformation.NetworkInformationException: Invalid access to memory location
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpConnections()
   at MadsKristensen.EditorExtensions.ServerBase.SelectAvailablePort()
   at MadsKristensen.EditorExtensions.ServerBase..ctor(String processStartArgumentsFormat, String serverPath)
   at MadsKristensen.EditorExtensions.NodeServer..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at MadsKristensen.EditorExtensions.ServerBase.<Up>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.NodeServer.<Up>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.NodeServer.<CallServiceAsync>d__1e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.NodeExecutorBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Scss.ScssCompiler.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.NodeCompilerRunner.<RunCompilerAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.CompilerRunnerBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.EditorCompilerInvoker.<InitiateCompilationAsync>d__4.MoveNext()

**Comment by Leefrost** [comment]
`Visual studio 12.0.31101.00 Update 4 .NET 4.5.51209`
`Web essentials 2013 for Update 4 ver 2.5.4 `

**Comment by PhilPatchett** [comment]
I get the same thing..  has this been resolved?

**Comment by rastapanda** [comment]
Restarting visual studio as admin fixed it for me. Admin maybe not required...

**Comment by rastapanda** [comment]
happened again admin not required to resolve.

**Comment by jhchau** [comment]
happens to me alot.  it is very frustrating...  will this be fixed or is there we can do to minimize this?

**Comment by jclementson** [comment]
+1
Same versions as above. Restarting VS does work as a workaround.

**Comment by KernelLeak** [comment]
If you're using a 64-bit operating system older than Windows 8 this seems to be a Windows bug:

http://blogs.msdn.com/b/cie/archive/2013/10/31/compute-emulator-invalid-access-to-memory-location.aspx
https://support.microsoft.com/en-us/kb/2588507

Haven't had time to try this yet, though...
