### ISSUE TITLE
Can't install WebEssentials 2013 on Visual Studio 2013 Community

### ISSUE THREAD

**Issue by aivascu** [madskristensen/WebEssentials2013#1795]
I used to have WebEssentials 2013 on my Visual Sudio 2013 Community but the SASS compilation sudennly stopped working. I assumed it was a WE2013 issue so I decided to reinstall.
Now I'm getting the "This extension is not installable on any currently installed products" message.
Here is the installation log:

05/03/2015 9:14:34 PM - Microsoft VSIX Installer
05/03/2015 9:14:34 PM - -------------------------------------------
05/03/2015 9:14:34 PM - Initializing Install...
05/03/2015 9:14:35 PM - Extension Details...
05/03/2015 9:14:35 PM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
05/03/2015 9:14:35 PM - 	Name            : Web Essentials 2013 for Update 4
05/03/2015 9:14:35 PM - 	Author          : Mads Kristensen
05/03/2015 9:14:35 PM - 	Version         : 2.5.4
05/03/2015 9:14:35 PM - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4
05/03/2015 9:14:35 PM - 	Locale          : en-US
05/03/2015 9:14:35 PM - 	MoreInfoURL     : http://vswebessentials.com/
05/03/2015 9:14:35 PM - 	InstalledByMSI  : False
05/03/2015 9:14:35 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
05/03/2015 9:14:35 PM - 
05/03/2015 9:14:35 PM - 	Supported Products : 
05/03/2015 9:14:35 PM - 		Microsoft.VisualStudio.Pro
05/03/2015 9:14:35 PM - 			Version : [12.0.31101]
05/03/2015 9:14:35 PM - 		Microsoft.VisualStudio.VWDExpress
05/03/2015 9:14:35 PM - 			Version : [12.0.31101]
05/03/2015 9:14:35 PM - 
05/03/2015 9:14:35 PM - 	References      : 
05/03/2015 9:14:35 PM - 
05/03/2015 9:14:35 PM - Searching for applicable products...
05/03/2015 9:14:35 PM - Found installed product - Microsoft Visual Studio Professional 2013
05/03/2015 9:14:35 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
05/03/2015 9:14:35 PM - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
05/03/2015 9:14:35 PM - Found installed product - Microsoft Visual Studio Premium 2015 CTP
05/03/2015 9:14:35 PM - Found installed product - Microsoft Visual Studio Professional 2015 CTP
05/03/2015 9:14:35 PM - Found installed product - Microsoft Visual Studio Community 2015 CTP
05/03/2015 9:14:35 PM - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
05/03/2015 9:14:35 PM - Found installed product - Global Location
05/03/2015 9:14:35 PM - Found installed product - ssms
05/03/2015 9:14:35 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by aivascu** [comment]
I don't know what the issue was but I uninstalled both versions of VS and installed a clean copy of the VS2013 Community and then the Web Essentials 2013 after that everything worked as usual.

**Comment by aivascu** [comment]
OK... so not everything went back to normal. The SASS stylesheets are still not compiling.

**Comment by ReedRichard** [comment]
I am now seeing this issue. I am a new user. I used the visual studio selector to try and install this. It worked for 2012 however I am trying to use 2013.

**Comment by jatin4pals** [comment]
Hey.. Even i am facing the same issue.. Please help.. This is the log for the same-

6/4/2015 11:40:48 AM - Microsoft VSIX Installer
6/4/2015 11:40:48 AM - -------------------------------------------
6/4/2015 11:40:53 AM - Initializing Install...
6/4/2015 11:40:55 AM - Extension Details...
6/4/2015 11:40:55 AM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
6/4/2015 11:40:55 AM - 	Name            : Web Essentials 2013 for Update 4
6/4/2015 11:40:55 AM - 	Author          : Mads Kristensen
6/4/2015 11:40:55 AM - 	Version         : 2.5.4
6/4/2015 11:40:55 AM - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4
6/4/2015 11:40:55 AM - 	Locale          : en-US
6/4/2015 11:40:55 AM - 	MoreInfoURL     : http://vswebessentials.com/
6/4/2015 11:40:55 AM - 	InstalledByMSI  : False
6/4/2015 11:40:55 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/4/2015 11:40:55 AM - 
6/4/2015 11:40:55 AM - 	Supported Products : 
6/4/2015 11:40:55 AM - 		Microsoft.VisualStudio.Pro
6/4/2015 11:40:55 AM - 			Version : [12.0.31101]
6/4/2015 11:40:55 AM - 		Microsoft.VisualStudio.VWDExpress
6/4/2015 11:40:55 AM - 			Version : [12.0.31101]
6/4/2015 11:40:55 AM - 
6/4/2015 11:40:55 AM - 	References      : 
6/4/2015 11:40:55 AM - 
6/4/2015 11:40:55 AM - Searching for applicable products...
6/4/2015 11:40:56 AM - Found installed product - Microsoft Visual Studio Professional 2013
6/4/2015 11:40:56 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
6/4/2015 11:40:56 AM - Found installed product - Global Location
6/4/2015 11:40:56 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by aivascu** [comment]
@jatin4pals completely uninstalling both VS 2013 and 2015 and reinstalling them fixed the problem for me. I would guess it's some compatibility issue between versions. Do you also have multiple VS IDEs with WebEssentials installed?
