### ISSUE TITLE
web essential install issue

### ISSUE THREAD

**Issue by ajaytgmercer** [madskristensen/WebEssentials2013#1872]
I am getting below error need help to resolve.

6/2/2015 8:51:26 AM - Microsoft VSIX Installer
6/2/2015 8:51:26 AM - -------------------------------------------
6/2/2015 8:51:26 AM - Initializing Install...
6/2/2015 8:51:27 AM - Extension Details...
6/2/2015 8:51:27 AM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
6/2/2015 8:51:27 AM - 	Name            : Web Essentials 2013 for Update 4
6/2/2015 8:51:27 AM - 	Author          : Mads Kristensen
6/2/2015 8:51:27 AM - 	Version         : 2.5.4
6/2/2015 8:51:27 AM - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4
6/2/2015 8:51:27 AM - 	Locale          : en-US
6/2/2015 8:51:27 AM - 	MoreInfoURL     : http://vswebessentials.com/
6/2/2015 8:51:27 AM - 	InstalledByMSI  : False
6/2/2015 8:51:27 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/2/2015 8:51:27 AM - 
6/2/2015 8:51:27 AM - 	Supported Products : 
6/2/2015 8:51:27 AM - 		Microsoft.VisualStudio.Pro
6/2/2015 8:51:27 AM - 			Version : [12.0.31101]
6/2/2015 8:51:27 AM - 		Microsoft.VisualStudio.VWDExpress
6/2/2015 8:51:27 AM - 			Version : [12.0.31101]
6/2/2015 8:51:27 AM - 
6/2/2015 8:51:27 AM - 	References      : 
6/2/2015 8:51:27 AM - 
6/2/2015 8:51:27 AM - Searching for applicable products...
6/2/2015 8:51:30 AM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
6/2/2015 8:51:30 AM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
6/2/2015 8:51:30 AM - Found installed product - Microsoft Visual Studio Professional 2013
6/2/2015 8:51:31 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
6/2/2015 8:51:31 AM - Found installed product - Global Location
6/2/2015 8:51:31 AM - Found installed product - ssms
6/2/2015 8:51:31 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by jatin4pals** [comment]
Even i am facing this same issue with visual studio pro 2013. Any further information on this, anyone?

**Comment by alejandroaldana** [comment]
I have the same issue. Any information about it?
