### ISSUE TITLE
Error on 'Create TypeScript Intellisense File' : A namespace may exist...

### ISSUE THREAD

**Issue by jhurdlow** [madskristensen/WebEssentials2013#1884]
When I right-click => Create TypeScript Intellisense File
on any of my SignalR Hub definitions I'm getting this error:
```
6/10/2015 4:46:15 PM: An error occurred while processing code in C:\BugReport\Hubs\BasicHub.cs
System.Runtime.InteropServices.COMException (0x80004005): A namespace may exist in multiple projects so it is not possible to retrieve the name through the ProjectItem
   at Microsoft.VisualStudio.CSharp.Services.Language.BaseException.ThrowEFAIL(ILangService iLangService, jrc_StringResource_identifiers stringId, Object[] args)
   at Microsoft.VisualStudio.CSharp.Services.Language.CodeModel.CExternalCodeElementBase.get_ProjectItem()
   at EnvDTE.CodeClass.get_ProjectItem()
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessElement(CodeElement element, List`1 list, HashSet`1 underProcess)
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessFile(ProjectItem item, HashSet`1 underProcess)
   at MadsKristensen.EditorExtensions.ScriptIntellisenseListener.<>c__DisplayClass1.<ProcessAsync>b__0()

Please report this bug at https://github.com/madskristensen/WebEssentials2013/issues, and include the source of the file.
```
Here's a simple example:
```C#
namespace MyBugExample.Hubs
{
	using Microsoft.AspNet.SignalR;
	using System.Collections.Generic;

	public class BasicHub : Hub<IBasicHubClient>
	{
		public void BroadcastAllStuff()
		{
			List<string> stuff = new List<string>();

			stuff.Add("Foo");
			stuff.Add("Bar");
			stuff.Add("Baz");

			Clients.All.newStuff(stuff);
		}
	}

	public interface IBasicHubClient
	{
		void newStuff(IEnumerable<string> stuff);
	}
}
```
There are no other uses of that namespace in the entire solution.
I am able to generate TypeScript Intellisense files from other simple class files in my project without any problems.
In fact, if I remove the inheritance on the hub (making it useless of course):
```C#
namespace MyBugExample.Hubs
{
	using Microsoft.AspNet.SignalR;
	using System.Collections.Generic;

	public class BasicHub // : Hub<IBasicHubClient>
	{
		public void BroadcastAllStuff()
		{
			List<string> stuff = new List<string>();

			stuff.Add("Foo");
			stuff.Add("Bar");
			stuff.Add("Baz");

			//Clients.All.newStuff(stuff);
		}
	}

	public interface IBasicHubClient
	{
		void newStuff(IEnumerable<string> stuff);
	}
}
```
It runs without errors and creates the following definition file:
```TypeScript
declare module server {
	interface BasicHub {
	}
}
```
Even then this is not what I'd expect. I would expect it to include the method:
```TypeScript
declare module server {
	interface BasicHub {
		broadcastStuff();
	}
}
```
In the end what I am (probably unrealistically) after from my original hub source would be something like this:
```TypeScript
interface SignalR {
	basicHub: BasicHubProxy;
}
interface BasicHubProxy {
	client: BasicHubClient;
	server: BasicHub;
}
interface BasicHubClient {
	newStuff(stuff: string[]);
}
interface BasicHub {
	broadcastAllStuff();
}
```
... with all the 'module server' stuff included of course.

To get to that end result may require another SignalR-aware tool be written, but even generating just the BasicHub interface without errors would be very helpful.

**Comment by redwyre** [comment]
I'm getting this as well, it's stopping the .d.ts files from being updated as well.
