### ISSUE TITLE
2.5.4 Bundle Error: File Does Not Exist

### ISSUE THREAD

**Issue by brentmclark** [madskristensen/WebEssentials2013#1913]
Getting the "Bundle Error: The file "\path\to\file.css" does not exist after installing version 2.5.4.  This is a fresh install of Web Essentials on a fresh install of VS 2013 Premier.  Bundles were built in VS 2012 using Web Essentials 3.8.  

I have uninstalled and reinstalled the extension a few times.  Ensured that the files exist at the stated path.  Tried logging in as an administrator.  Taken ownership of the files.  

There has been no joy.  Please advise.

**Comment by brentmclark** [comment]
Output Window shows the following:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleGenerator.<CombineFiles>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleGenerator.<MakeBundle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
7/16/2015 11:19:42 AM: Error generating the bundle. See output window for details
7/16/2015 11:19:43 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleGenerator.<CombineFiles>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleGenerator.<MakeBundle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
7/16/2015 11:19:43 AM: Error generating the bundle. See output window for details
7/16/2015 11:19:47 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleGenerator.<CombineFiles>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleGenerator.<MakeBundle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
7/16/2015 11:19:47 AM: Error generating the bundle. See output window for details
7/16/2015 11:19:52 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BundleGenerator.<CombineFiles>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleGenerator.<MakeBundle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
7/16/2015 11:19:52 AM: Error generating the bundle. See output window for details

**Comment by madskristensen** [comment]
There might  be a version difference between the 2012 format and the 2013. Try to recreate the bundles in 2013

**Comment by brentmclark** [comment]
No difference in schema, but generating the bundle on 2013 defaults to paths relative to the project instead of the solution.  Changing the path of the first file in the bundle to be relative to the project shifts the error message target to the next file in the group, but now I need to figure out if this pathing change is backwards compatible.  We are in a mixed environment, and will be for some time.

**Comment by brentmclark** [comment]
Also, thanks for the lightning-fast response!  Classy.

**Comment by brentmclark** [comment]
Taking the name of the project out of the relative file path fixes this issue.  Thanks for your time!
