### ISSUE TITLE
 System.NullReferenceException in AngularLogoCompletion in 0.5.144

### ISSUE THREAD

**Issue by alexeyzimarev** [madskristensen/WebEssentials2013#1936]
Constantly observing multiple error messages in the Build output

05/08/2015 13:49:26: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.get_CompletionSets()
   at MadsKristensen.EditorExtensions.Html.AngularLogoCompletion.<>c__DisplayClass4_0.<ChangeIcons>b__0() in C:\projects\webessentials2015\EditorExtensions\HTML\Completion\AngularLogoCompletion.cs:line 35

**Comment by erictor** [comment]
Visual Studio 2015 RTM:  8/23/2015 6:41:41 PM: System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft. VisualStudio. Language. Intellisense. Implementation. CompletionSession. get_CompletionSets()  at MadsKristensen. EditorExtensions. Html. AngularLogoCompletion.<>c__DisplayClass4_0.<ChangeIcons>b__0() in C:\projects \webessentials2015 \EditorExtensions \HTML \Completion \AngularLogoCompletion.cs:line 35

**Comment by frederikprijck** [comment]
I have the exact same problem in VS 2015 Enterprise using WebEssentials 0.5.168

```
9/3/2015 11:06:39 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.get_CompletionSets()
   at MadsKristensen.EditorExtensions.Html.AngularLogoCompletion.<>c__DisplayClass4_0.<ChangeIcons>b__0() in C:\projects\webessentials2015\EditorExtensions\HTML\Completion\AngularLogoCompletion.cs:line 35
```
