### ISSUE TITLE
VS2015 CE on WIN10 Crashes When Opening Any File After Latest Update

### ISSUE THREAD

**Issue by stottster** [madskristensen/WebEssentials2013#1940]
Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f3b2a
Exception code: 0xe0434352
Fault offset: 0x000b3e28
Faulting process ID: 0x1bb8
Faulting application start time: 0x01d0d5ac8e693765
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report ID: c57f5dff-e709-40b4-81b5-28d32923e04b
Faulting package full name: 
Faulting package-relative application ID: 

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c__DisplayClass2.<ThrowAsync>b__3(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by madskristensen** [comment]
The callstack doesn't list any WE assemblies?

**Comment by stottster** [comment]
What can I say, if I disable the extension I can use VS fine (F# interactive, PTVS, SSDT, etc), but once enabled the IDE, loads OK, start page visible (showing web content), F# console functional (sorry 😜), but when an attempt to open *any* (random text file, solution item, under VCS or not, in OneDrive or not) file is made it crashes, leaving just those two events in the log. 
I have run DevEnv.exe /Log ... but there is nothing extraordinary in the log it produces - IIRC it even logs successful WebEssentials package loading).
I'm not overly concerned because I can get on with my work, just thought Id 'put it out there' in case anyone else has the same problem.
Just as an aside, I have another machine with identical software installed, other than the OS is W7SP1 and it is joined to a domain, and this machine does not exhibit the same problem.

**Comment by stottster** [comment]
Accidentally closed - reopened
