### ISSUE TITLE
I can not able to install web essential 2013 in to my vs 2013 ultimate

### ISSUE THREAD

**Issue by nisarg18** [madskristensen/WebEssentials2013#1952]
I can not able to install web essential 2013 in to my vs 2013 ultimate

Install log is as below.

12-09-2015 6:53:49 AM - Microsoft VSIX Installer
12-09-2015 6:53:49 AM - -------------------------------------------
12-09-2015 6:53:49 AM - Initializing Install...
12-09-2015 6:53:50 AM - Extension Details...
12-09-2015 6:53:50 AM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
12-09-2015 6:53:50 AM - 	Name            : Web Essentials 2013 for Update 4 RC
12-09-2015 6:53:50 AM - 	Author          : Mads Kristensen
12-09-2015 6:53:50 AM - 	Version         : 2.4
12-09-2015 6:53:50 AM - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4 RC
12-09-2015 6:53:50 AM - 	Locale          : en-US
12-09-2015 6:53:50 AM - 	MoreInfoURL     : http://vswebessentials.com/
12-09-2015 6:53:50 AM - 	InstalledByMSI  : False
12-09-2015 6:53:50 AM - 	SupportedFrameworkVersionRange : [4.5]
12-09-2015 6:53:50 AM - 
12-09-2015 6:53:50 AM - 	Supported Products : 
12-09-2015 6:53:50 AM - 		Microsoft.VisualStudio.Pro
12-09-2015 6:53:50 AM - 			Version : [12.0.31010]
12-09-2015 6:53:50 AM - 		Microsoft.VisualStudio.VWDExpress
12-09-2015 6:53:50 AM - 			Version : [12.0.31010]
12-09-2015 6:53:50 AM - 
12-09-2015 6:53:50 AM - 	References      : 
12-09-2015 6:53:50 AM - 		-------------------------------------------------------
12-09-2015 6:53:50 AM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
12-09-2015 6:53:50 AM - 		Name         : Visual Studio MPF 12.0
12-09-2015 6:53:50 AM - 		Version      : [12.0,13.0)
12-09-2015 6:53:50 AM - 		MoreInfoURL  : 
12-09-2015 6:53:50 AM - 		Nested       : No
12-09-2015 6:53:50 AM - 
12-09-2015 6:53:50 AM - 
12-09-2015 6:53:50 AM - Searching for applicable products...
12-09-2015 6:53:51 AM - Found installed product - Microsoft Visual Studio 2010 Professional
12-09-2015 6:53:51 AM - Found installed product - Microsoft Visual Studio Express 2012 for Web
12-09-2015 6:53:51 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
12-09-2015 6:53:51 AM - Found installed product - Microsoft Visual Studio Premium 2013
12-09-2015 6:53:51 AM - Found installed product - Microsoft Visual Studio Professional 2013
12-09-2015 6:53:51 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
12-09-2015 6:53:51 AM - Found installed product - Global Location
12-09-2015 6:53:51 AM - Found installed product - ssms
12-09-2015 6:53:51 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Thanks & Regards
Nisarg Soni

**Comment by KenHolt21** [comment]
I've experienced the exact same problem just now. Here's the install log details:-

15/09/2015 10:16:30 - Microsoft VSIX Installer
15/09/2015 10:16:30 - -------------------------------------------
15/09/2015 10:16:30 - Initializing Install...
15/09/2015 10:16:31 - Extension Details...
15/09/2015 10:16:31 - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
15/09/2015 10:16:31 - 	Name            : Web Essentials 2013.5
15/09/2015 10:16:31 - 	Author          : Mads Kristensen
15/09/2015 10:16:31 - 	Version         : 2.6.36
15/09/2015 10:16:31 - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4 or 5
15/09/2015 10:16:31 - 	Locale          : en-US
15/09/2015 10:16:31 - 	MoreInfoURL     : http://vswebessentials.com/
15/09/2015 10:16:31 - 	InstalledByMSI  : False
15/09/2015 10:16:31 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
15/09/2015 10:16:31 - 
15/09/2015 10:16:31 - 	Supported Products : 
15/09/2015 10:16:31 - 		Microsoft.VisualStudio.Pro
15/09/2015 10:16:31 - 			Version : [12.0.31101,13.0)
15/09/2015 10:16:31 - 
15/09/2015 10:16:31 - 	References      : 
15/09/2015 10:16:31 - 
15/09/2015 10:16:31 - Searching for applicable products...
15/09/2015 10:16:31 - Found installed product - Microsoft Visual Studio Professional 2013
15/09/2015 10:16:31 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
15/09/2015 10:16:31 - Found installed product - Global Location
15/09/2015 10:16:31 - Found installed product - ssms
15/09/2015 10:16:31 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by sbryfcz** [comment]
Did you guys ever figure it out?

**Comment by madskristensen** [comment]
You need Visual Studio 2013 Update 4 or 5 to install it
