### ISSUE TITLE
ArgumentException during build

### ISSUE THREAD

**Issue by gkappen** [madskristensen/WebEssentials2013#1975]
I get this:
System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder(Project project)
when I build, but only if I start the build and have a project properties page open as my active document

**Comment by GProulx** [comment]
Hi,

Do you use the latest version of WebEssentials? What is the project type?

**Comment by brentljohnson** [comment]
Same issue for me.  Tried updating to the latest version (2.6.36) but no improvement.  Appears in the Build Output window for any project type (website, database, WIX, etc.):

========== Build: 2 succeeded, 0 failed, 10 up-to-date, 1 skipped ==========
4/12/2015 8:14:55 a.m.: System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder(Project project)
4/12/2015 8:14:55 a.m.: System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder(Project project)
4/12/2015 8:14:55 a.m.: System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder(Project project)
4/12/2015 8:14:55 a.m.: System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder(Project project)

**Comment by MarkusNeviadomski** [comment]
Same here with Web Essentials 2.6.36 and VS 2013 Ultimate in a Sharepoint solution:
========== Deploy: 4 succeeded, 0 failed, 0 skipped ==========
10.01.2016 20:00:38: System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder(Project project)
10.01.2016 20:00:38: System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder(Project project)

**Comment by bambit** [comment]
I can confirm brentljohnson's comment, Error appears whenever properties window has focus during a build.  
VS 2013 Professional Version 12.0.40629.00 Update 5
Web Essentials version 2.6.36

**Comment by stevomccormack** [comment]
I'm getting this as well in VS 2017 Professional
Version: 15.1 (26403.7)

I am confident this is causing build issues. I cannot build my projects at all. I need to start/restart/again/again/again until finally somehow the build works. I have been trying to diagnose the root cause for many months now. I had some node errors (around ssh) that I thought may be issue - perhaps causing problems with gulp file locking but I have resolved those issues. The only outstanding error I am getting in VS is this one.
