### ISSUE TITLE
Could not load file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by enihcam** [madskristensen/WebEssentials2013#1982]
12/24/2015 5:44:07 PM: An exception was thrown when running solution-wide compilers: System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'MadsKristensen.EditorExtensions.Settings.WESettings' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ConfOxide.MemberAccess.TypeAccessor`1' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at ConfOxide.MemberAccess.TypedPropertyAccessor`2.GetJsonName(PropertyInfo property)
   at ConfOxide.MemberAccess.TypedPropertyAccessor`2..ctor(PropertyInfo property)
   at ConfOxide.MemberAccess.NestedPropertyAccessor`2..ctor(PropertyInfo property)

Which folder shall I put 'Newtonsoft.Json.dll' into?

**Comment by GProulx** [comment]
Hi!

Do you use the last version of WebEssentials 2013? Did you receive this error message while compiling?

You should not have to copy Json.net dll anywhere. It supposes to be included into WebEssentials assembly.

**Comment by chrisahhh** [comment]
Hi, I've got the same issue. Using VS 2013, latest version. If I open a .scss or .ts file then it will show an error saying an error has occurred, if I then try to edit the file VS crashes and has an option to debug with the cited exception
