### ISSUE TITLE
projectSystem.ArgumentException: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by ewilli** [madskristensen/WebEssentials2013#2012]
VS2015: Open project properties. Then right - click on project in Solution Explorer:

16.8.2016 11:27:06: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 221
16.8.2016 11:27:06: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 221

**Comment by ewilli** [comment]
Wrong Version -> 2015
