### ISSUE TITLE
I can't install web essentials 2017 to vs 2017

### ISSUE THREAD

**Issue by stevenahanson** [madskristensen/WebEssentials2013#2029]
Hi, 

I am having issues in installing web essentials 2017 to visual studio 2017 (community). 

This extension is not installable on any currently installed  products.

Please see log below:

09/01/2018 13:34:38 - Microsoft VSIX Installer
09/01/2018 13:34:38 - -------------------------------------------
09/01/2018 13:34:38 - vsixinstaller.exe version:
09/01/2018 13:34:38 - 15.0.26430.16 built by: D15SVC
09/01/2018 13:34:38 - -------------------------------------------
09/01/2018 13:34:38 - Command line parameters:
09/01/2018 13:34:38 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\Steven\Downloads\Web Essentials 2017 v1.5.34.vsix
09/01/2018 13:34:38 - -------------------------------------------
09/01/2018 13:34:38 - Microsoft VSIX Installer
09/01/2018 13:34:38 - -------------------------------------------
09/01/2018 13:34:38 - Failed to initialize settings for Isolated Shell c:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
09/01/2018 13:34:50 - Initializing Install...
09/01/2018 13:34:53 - Extension Details...
09/01/2018 13:34:53 - 	Identifier         : bb7e2273-9a70-4e5e-b4dd-1f361b6166c0
09/01/2018 13:34:53 - 	Name               : Web Essentials 2017
09/01/2018 13:34:53 - 	Author             : Mads Kristensen
09/01/2018 13:34:53 - 	Version            : 1.5.34
09/01/2018 13:34:53 - 	Description        : The easiest way to set up Visual Studio for the ultimate web development experience. Requires Visual Studio 2017 Update 3 or newer
09/01/2018 13:34:53 - 	Locale             : en-US
09/01/2018 13:34:53 - 	MoreInfoURL        : https://github.com/madskristensen/WebEssentials2017
09/01/2018 13:34:53 - 	InstalledByMSI     : False
09/01/2018 13:34:53 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
09/01/2018 13:34:53 - 
09/01/2018 13:34:53 - 	SignatureState     : Unsigned
09/01/2018 13:34:53 - 	Supported Products : 
09/01/2018 13:34:53 - 		Microsoft.VisualStudio.Pro
09/01/2018 13:34:53 - 			Version : [15.0.26431,16.0)
09/01/2018 13:34:53 - 
09/01/2018 13:34:53 - 	References         : 
09/01/2018 13:34:53 - 	Prerequisites      : 
09/01/2018 13:34:53 - 		-------------------------------------------------------
09/01/2018 13:34:53 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
09/01/2018 13:34:53 - 		Name         : Visual Studio core editor
09/01/2018 13:34:53 - 		Version      : [15.0,16.0)
09/01/2018 13:34:53 - 
09/01/2018 13:34:53 - 		-------------------------------------------------------
09/01/2018 13:34:53 - 		Identifier   : Microsoft.VisualStudio.Component.Web
09/01/2018 13:34:53 - 		Name         : Web development tools
09/01/2018 13:34:53 - 		Version      : [15.0,16.0)
09/01/2018 13:34:53 - 
09/01/2018 13:34:53 - Signature Details...
09/01/2018 13:34:53 - 	Extension is not signed.
09/01/2018 13:34:53 - 
09/01/2018 13:34:53 - Searching for applicable products...
09/01/2018 13:34:53 - Found installed product - Microsoft Visual Studio 2010 Ultimate
09/01/2018 13:34:53 - Found installed product - Global Location
09/01/2018 13:34:53 - Found installed product - Visual Studio Community 2017
09/01/2018 13:34:53 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by GProulx** [comment]
Hi,

You should log the issue on the WE2017 repository: https://github.com/madskristensen/WebEssentials2017/issues
