### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by lennybacon** [madskristensen/WebEssentials2013#444]
I get an error and a warning in chrome using a static file with no debugger attached:

event.returnValue is deprecated. Please use the standard event.preventDefault() instead. browserLink:37
[23:56:22 GMT+0100 (W. Europe Standard Time)] Browser Link: Exception thrown when trying to invoke Browser Link extension callback "madskristensen.editorextensions.browserlink.unusedcss.unusedcssextensionfactory.GetIgnoreList":
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BrowserLink.UnusedCss.UnusedCssExtension.GetIgnoreList()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Web.BrowserLink.ClientMessaging.DispatchMessage(BrowserLinkConnection connection, MessageArgs obj)
 browserLink:64
[23:56:23 GMT+0100 (W. Europe Standard Time)] Browser Link: Exception thrown when trying to invoke Browser Link extension callback "madskristensen.editorextensions.bestpracticesfactory.Error":
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.BestPractices.AddHierarchyItem(ErrorTask task)
   at MadsKristensen.EditorExtensions.BestPractices.CreateTask(String id, IRule rule, Boolean success)
   at MadsKristensen.EditorExtensions.BestPractices.Error(String id, Boolean success, String data)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Web.BrowserLink.ClientMessaging.DispatchMessage(BrowserLinkConnection connection, MessageArgs obj)
 browserLink:64

**Comment by HelloBugs** [comment]
I get the exactly the same thing. I'm using VS2013 and Web Essentials 2013 for Update 4
