### ISSUE TITLE
/__browserLink/requestData: Input string was not in a correct format.

### ISSUE THREAD

**Issue by StefanSchoof** [madskristensen/WebEssentials2013#851]
In my Environment BrowserLink does not work (No F12 changes are saved and Unused CSS does not have any effect, a reload from VS triggers does work) OOn the Load of the Page is a Request to /AppName/__browserLink/requestData/9422826f1daa40a9bfdf09f4a252ff83 (the id changes) which returns a 500 Server Error with the Exception:

```
[FormatException]: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.MappingData.MappingDataUtilities.GenerateSelectorsForElementsWithTagName(List`1 elements, String selectorFormatString, SelectorGroupFunction[] groupMethods, Int32 startIndex)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.MappingData.MappingDataUtilities.GenerateSelectorsForElementsWithTagName(List`1 elements, String selectorFormatString, SelectorGroupFunction[] groupMethods, Int32 startIndex)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.MappingData.MappingDataUtilities.GenerateSelectorsForElementsWithTagName(List`1 elements, String selectorFormatString, SelectorGroupFunction[] groupMethods, Int32 startIndex)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.MappingData.MappingDataUtilities.GenerateSelectorsWorker(IEnumerable`1 elements, String selectorFormatString, SelectorGroupFunction[] groupMethods)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.MappingData.MappingDataUtilities.GenerateSelectors(IEnumerable`1 elements)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.MappingData.MappingDataUtilities.ProcessDataIntoJsonObjects(IEnumerable`1 renderedOutputList)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.Tracing.RequestDataHttpHandler.System.Web.IHttpHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

I Run Visual Studio 2013 Update 2 RC 2 with Web Essentials2013 2.0 on a Windows Server 2008 R2. I use the IIS (not the IISExpress). It is a ASP.NET MVC 5.1.1 WebApp

**Comment by Bmadhava** [comment]
http://codemust.com/browser-link-feature-in-visual-studio-2013/

This will solve your problems.

 Set appSetting “vs:EnableBrowserLink” to “false ““. This will  disable Browser Link.

  <appSettings>    
    <add key="vs:EnableBrowserLink" value="false"/>
  </appSettings>

**Comment by Coding-Keeda** [comment]
thanks a lot buddy It worked.@Bmadhava
